# Generated by Django 3.1.3 on 2021-02-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('plan_validity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField()),
                ('user_enrolled', models.PositiveIntegerField()),
            ],
        ),
    ]
