# Generated by Django 3.1.3 on 2021-02-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentFeature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='name',
        ),
        migrations.AddField(
            model_name='feature',
            name='body',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
