# Generated by Django 3.1.3 on 2021-01-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentFeature', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='feature',
            name='image_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='total_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
