# Generated by Django 3.1.3 on 2021-02-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentUpload', '0002_delete_documentfeature'),
        ('DocumentFeature', '0002_auto_20210209_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='docs_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DocumentUpload.uploadfiles'),
            preserve_default=False,
        ),
    ]
