# Generated by Django 3.1.3 on 2021-01-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentFeature', '0002_auto_20210107_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='etc',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='image_count',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='total_pages',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='word_count',
        ),
    ]
