# Generated by Django 3.1.3 on 2021-01-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentFeature', '0003_auto_20210129_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='title',
            new_name='name',
        ),
    ]
