# Generated by Django 3.1.3 on 2021-02-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentUpload', '0002_delete_documentfeature'),
        ('DocumentFeature', '0003_feature_docs_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature',
            new_name='ResultFeature',
        ),
    ]
