# Generated by Django 3.1.3 on 2021-01-04 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('upload_file', models.FileField(upload_to='files/')),
                ('file_size', models.FloatField(default=0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('category', models.CharField(default='Unknown', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Files',
                'verbose_name_plural': 'Upload Files',
            },
        ),
    ]
