# Generated by Django 3.1.3 on 2021-02-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentUpload', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentFeature',
        ),
    ]
