# Generated by Django 3.1.3 on 2021-01-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentUpload', '0002_documentfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
