# Generated by Django 3.1.3 on 2021-01-11 13:44

import DocumentUpload.services.driveupload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentUpload', '0003_auto_20210108_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='file_size',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='upload_file',
            field=models.FileField(storage=DocumentUpload.services.driveupload.get_gd_storage, upload_to='files/'),
        ),
    ]
