# Generated by Django 3.1.3 on 2021-01-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentUpload', '0004_auto_20210111_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='file_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
