# Generated by Django 3.1.3 on 2021-01-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentUpload', '0005_auto_20210111_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
