# Generated by Django 3.1.3 on 2021-01-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentUpload', '0006_auto_20210111_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
