# Generated by Django 3.1.3 on 2021-01-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentUpload', '0007_auto_20210111_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='upload_file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
