# Generated by Django 3.1.3 on 2020-11-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20201130_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
